### ISSUE TITLE
Mod metadata not appearing in PrismLauncher

### ISSUE THREAD

**Issue by OpenBagTwo** [isXander/YetAnotherConfigLib#175]
Mod version: YetAnotherConfigLib-3.4.2+1.20.4-fabric.jar
Minecraft version: 1.20.4
Loader: Fabric 0.15.3
Launcher: PrismLauncher 8.3 Flatpak (Linux), PrismLauncher 7.2 macOS

## Describe the problem

PrismLauncher shows the mod's name as `${name}` and the version as `${version}`. This has happened for none of my other mods, nor prior versions of YACL.

This appears to be strictly cosmetic—I've had no issues with running instances with the mod, nor does this incorrect name / version appear in the game logs.

![Screenshot from 2024-05-05 11 00 50](https://github.com/isXander/YetAnotherConfigLib/assets/66568922/b507c908-d60f-4455-be44-4c6a9e93ad1d)

![Screenshot from 2024-05-05 11 00 41](https://github.com/isXander/YetAnotherConfigLib/assets/66568922/e1bd5c62-7146-4c7d-a229-0efcfe9b8e02)

## Steps to reproduce
1. Create a PrismLauncher instance (Minecraft 1.20.4, Fabric)
2. Add YACL as a mod, either through the built-in downloader (I sourced from Modrinth) or by downloading the JAR straight from the release page

## Affected Systems

I've reproduced this both on macOS and Linux versions of PrismLauncher and also an old ManyMC instance. I have no idea if this issue affects other, non-MMC-style launchers.

## Severity

Again, this is strictly cosmetic

**Comment by rvbsm** [comment]
Can confirm this too. `mods.toml` and `neoforge.mods.toml` aren't processed during the build.

```toml
modLoader = "javafml"
loaderVersion = "${loaderVersion}"
#issueTrackerURL = ""
license = "LGPL-3.0-or-later"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "isXander"
description = '''
${description}
'''
logoFile = "yacl-128x.png"

[[mixins]]
config = "yacl.mixins.json"

[["dependencies.${id}"]]
modId = "${forgeId}"
mandatory = true
versionRange = "${forgeConstraint}"
ordering = "NONE"
side = "BOTH"

[["dependencies.${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${mc}"
ordering = "NONE"
side = "BOTH"
```

For some reason, launcher reads metadata from `META-INF/mods.toml`, even if instance is using Fabric Loader
